// <auto-generated />
using System;
using EmployeeManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace EmployeeManagementSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagementSystem.Models.Employee", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("FirstName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Email").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Phone").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Department").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("JobTitle").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<DateTime>("DateOfJoining").HasColumnType("datetime2");
                b.Property<decimal>("Salary").HasColumnType("decimal(18,2)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("ProfilePicture").HasColumnType("nvarchar(max)");
                b.Property<string>("Address").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("Employees");
            });
#pragma warning restore 612, 618
        }
    }
}
